# syntax=docker/dockerfile:1
FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app
COPY MessageProcessing/target/MessageProcessing-0.0.1-SNAPSHOT.jar MessageProcessing-0.0.1-SNAPSHOT.jar
CMD java -jar MessageProcessing-0.0.1-SNAPSHOT.jar $KAFKABOOTSTRAPSERVER
