# syntax=docker/dockerfile:1
FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app
COPY BotTg/target/BotTg-0.0.1-SNAPSHOT.jar BotTg-0.0.1-SNAPSHOT.jar
CMD java -jar BotTg-0.0.1-SNAPSHOT.jar $TGBOTCREDENTIALS $KAFKABOOTSTRAPSERVER
